### ISSUE TITLE
Can not figure out how to print numbers in format.

### ISSUE THREAD

**Issue by dvdsk** [danieldg/rwaybar#9]
Hi daniel,

Recently I have added a new widget to my bar. This widget (not made by me) outputs the following json:
```json
{"msg": "Anki - due: 306, new: 1", "due": 306, "new": 1}
```

Note how the value corresponding to the key due is a number not a string.

My config then reads as follows:
```toml
[[bar]]
... other config (irrelevant for this issue)
left = ["workspaces", "break-enforcer"]
center= ["clock"]
right = ["pm2_5", "temperature", "humidity", "anki", "tray"]
... other config (irrelevant for this issue)

[anki-cmd]
type = "exec-json"
command = "anki-widget --json --path /home/david/.var/app/net.ankiweb.Anki/data/Anki2 continuous"

[anki]
format = "{anki-cmd.due}"
margin = "0 10"
```

Nothing appears in the bar. If I change the format to: `format = "{anki-cmd.msg}"` then 'Anki - due: 306, new: 1' appears in the bar.
